spring:
  application.name: urlshortener
  profiles.active: dev

  jackson:
    time-zone: "Asia/Seoul"
    serialization:
      write-dates-as-timestamps: true


server:
  port: 8080
  forward-headers-strategy: native

  netty:
    connection-timeout: 30
    max-keep-alive-requests: 50


logging:
  level:
    root: INFO
    org.springframework: INFO
    net.rubyworks.urlshortener: DEBUG



---
spring:
  config.activate.on-profile: dev

  data:
    redis:
      host: localhost
      port: 6379
      database: 0


app_props:
  shortener-url: http://localhost:8080
  home-url: http://localhost:8080





---
spring:
  config.activate.on-profile: product

  data:
    redis:
      host: redis
      port: 6379
      database: 0


app_props:
  shortener-url: https://s.dii.im
  home-url: https://www.dii.im

